version: '2'
services:
  database:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=kochbuch-root-pw"
      - "MYSQL_USER=kochbuch"
      - "MYSQL_PASSWORD=kochbuch-user-pw"
      - "MYSQL_DATABASE=kochbuch"
    ports:
      - 3306:3306
    volumes:
      - database-volume:/var/lib/mysql
volumes:
  database-volume: