version: '2'
services:
  database:
    image: mysql
    environment:
      - "MYSQL_DATABASE=kochbuch"
    volumes:
      - database-volume:/var/lib/mysql
  backend:
    image: r.patrick246.de/inf16a/kochbuch-backend
    links:
      - database:db
volumes:
  database-volume: