version: '2'
services:
  database:
    image: mysql
    environment:
      - "MYSQL_DATABASE=kochbuch"
    volumes:
      - database-volume:/var/lib/mysql
  backend:
    image: r.patrick246.de/inf16a/kochbuch-backend
    links:
      - database:db
    ports:
      - 127.0.0.1:8085:8080
volumes:
  database-volume: